### ISSUE TITLE
Spacing between list items is too big

### ISSUE THREAD

**Issue by AppiePau** [christiaanderidder/QuestPDF.Markdown#19]
**Describe the bug**

**To Reproduce**
Using the following code, I get an unordered list with a lot of white space between the lines. Using the debugger it seems that every bullet point is placed in it's own paragraph.
```
+ Test
+ Test
+ Test
````
or a full example:
```
var document = Document.Create(container =>
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(1, Unit.Centimetre);
            page.PageColor(Colors.White);
            page.DefaultTextStyle(x => x.FontSize(10));

            page.Content().Row(row =>
            {

                row.RelativeItem(1)
                    .Markdown("Test line above list.\r\n* Test\r\n* Test\r\n* Test");
            });
        });
    });

document.GeneratePdfAndShow();
```

**Expected behavior**
I would like to see the bullet points in one paragraph and each bullet point on a new line, resulting each line without the white space. Wether this is default behavior or configurable is less of a concern to me. It just seems more logical for me to have items of the same list without whitespace. Just like in HTML `<ul>` with `<li>` behavior. Like:
<ul>
<li>Test</li>  
<li>Test</li>  
<li>Test</li>  
</ul>

**Screenshots**
<img width="466" alt="Screenshot 2023-12-20 at 21 10 53" src="https://github.com/christiaanderidder/QuestPDF.Markdown/assets/12054734/8a879a15-f3bc-4e99-877f-9ddf52947334">

Note: Only the Test bullets are part of the Markdown code. The rest of layout/texts are not.
I can reproduce this behavior in various places.

<img width="558" alt="Screenshot 2023-12-20 at 16 45 44" src="https://github.com/christiaanderidder/QuestPDF.Markdown/assets/12054734/2265873d-ada7-40a8-a1be-8ea7c1d3a9ad">

**Environment (please complete the following information):**
 - OS and version:  macOS 14 Sonoma
 - OS Platform x64, arm64
 -  QuestPDF 2023.12.1
 - QuestPDF.Markdown 1.3.0

**Additional context**
No comments at this moment.

**Comment by christiaanderidder** [comment]
Thanks for submitting this issue. The nested paragraphs seem to be a limitation of how markdig renders the markdown document, but it should be no issue to make the spacings within lists configurable. This think should address your issue.
