### ISSUE TITLE
More options to configure table ?

### ISSUE THREAD

**Issue by screwyourshelf** [christiaanderidder/QuestPDF.Markdown#49]
Dunno if this is the correct place to register "requests". One thing I would find highly useful is a way to specify padding and border (top,bottom,etc) for Header and Cell Elements: The This feature would allow for a more refined and visually appealing presentation of table data, accommodating various design requirements and improving readability.

Good work so far , thanks

**Comment by christiaanderidder** [comment]
Hi,

For now I tried to keep the markup options as simple as possible, to stick with the simplicity of markdown. There are some ways to configure the behavior of how a table is rendered (see: https://github.com/christiaanderidder/QuestPDF.Markdown/blob/main/src/QuestPDF.Markdown/MarkdownRendererOptions.cs).

That being said, I am open to PRs adding the suggested improvements.
