### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by lukas9812** [christiaanderidder/QuestPDF.Markdown#92]
Hello @christiaanderidder ,
I want to ask regarding a licencing for this package.
I know that original QuestPdf has Enterprise and Proffesional licence, so do I need to have paid it for commercial use ? (We have a project where we want to generate a PDF document with figures as one of the features.) Or is licencing already resolved within your package and QuestPDF ? 

Many thanks
Lukas

**Comment by christiaanderidder** [comment]
Hi @lukas9812 

This package is released under the MIT license, and as such you can do as you please with the code, including using it in a commercial product.

However, the code in this package provides just the glue between parsing markdown and formatting PDF documents in QuestPDF.
This means that you still require QuestPDF to make it work and need to configure your QuestPDF license.
QuestPDF does require purchasing a license for commercial use, see https://www.questpdf.com/license/configuration.html

**Comment by lukas9812** [comment]
Thank you a lot @christiaanderidder
