### ISSUE TITLE
HTML inside the markdown is not rendered.

### ISSUE THREAD

**Issue by DominikFG** [christiaanderidder/QuestPDF.Markdown#96]
**Describe the bug**
I have some HTML inside my Markdown I want to render to a PDF. 
But it is not rendered as HTML. I can't remove the HTML since I get those snippets from a source that is already HTML formatted.

Is this a bug or is my configuration wrong?

**To Reproduce**
Sample code that produces the error
```csharp
var stringBuilder = new StringBuilder();

stringBuilder.AppendLine("Lorem ipsum dolor sit amet\n<p><strong>consetetur :</strong> sed diam nonumy eirmod tempor.</p><p><strong>invidunt:</strong> labore et dolore magna aliquyam erat</p>");

using var pdfStream = new FileStream("output.pdf", FileMode.Create);
var options = new MarkdownRendererOptions { Debug = true };
var markdown = ParsedMarkdownDocument.FromText(stringBuilder.ToString());

var document = Document.Create(container =>
{
    container.Page(page =>
    {
        page.Size(PageSizes.A4);
        page.Margin(1, Unit.Centimetre);
        page.Content().Markdown(markdown, options);
    });
});
document.GeneratePdf(pdfStream);
```

**Expected behavior**
![expected PDF result](https://github.com/user-attachments/assets/b904c27f-cc9d-4895-a0e8-10b4e1ee97f5)

**Screenshots**
![rendered PDF](https://github.com/user-attachments/assets/f9c5e7fb-6779-43f3-a3ef-f13e9af4521f)

**Environment (please complete the following information):**
 - OS and version: win11
 - OS Platform x64
 - QuestPDF Version 2024.10.4 Community License
 - QuestPDF.Markdown Version 1.26.0

**Comment by christiaanderidder** [comment]
Hi @DominikFG,

This is not a bug, but simply something that is not supported.
QuestPDF.Markdown does not support HTML-to-PDF conversion, it's a Markdown-to-PDF converter that supports pure markdown only. Raw HTML is not supported.

The reason for this is that HTML comes with many additional issues and almost all existing converters have issues with it, often leading to people having to use full headless browser engines to make it work.

Markdown offers a way to have users add input for generated PDFs without having such challenges and that is what this library provides.

**Comment by DominikFG** [comment]
Thanks for your response.

From [the test document](https://github.com/christiaanderidder/QuestPDF.Markdown/blob/main/tests/QuestPDF.Markdown.Tests/test.md#inline-html) I understood that inline HTML is (partially) supported.
